name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make get-stockfish
      run: make get-stockfish
    - name: make
      run: make
    - name: test
      run: ./d3 test -quick
